### ISSUE TITLE
why only one read of paired-end data is used for mapping ?

### ISSUE THREAD

**Issue by Maschi88** [shunliubio/eTAM-seq_workflow#7]
Hello,

Thank you for the eTAM-seq workflow, I'm interesting in using this technology in my lab. 

While studying your workflow, I'm a bit lost about the type of data you're using. eTAM-seq is described as a modified RNA-seq experiment, paired-end sequencing, so why in your workflow, at step 2, hisat-3n is using only R2 ? 
Wouldn't it make sense to use both ? Or maybe R1 is here for some technical reason and then unnecessary for mapping (e.g. like in single cell RNA-seq) ?

Thanks and have a nice day.

**Comment by shunliubio** [comment]
Hi,

It is related to the technical issue. Some sequencing instruments like NextSeq or NovaSeq use a two-color sequencing system with `G` being dark. It can't distinguish no signal from `G`. Too many dark cycles will impact sequencing quality. That's why R1 tends to have lower quality.

Also read the [link](https://sequencing.qcfail.com/articles/illumina-2-colour-chemistry-can-overcall-high-confidence-g-bases/) for reference.

**Comment by Maschi88** [comment]
Oh, I didn't think about that. Indeed, it makes sense now, thanks a lot for the answer.
